import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Index.module.css'
import Card from "../components/card";
import { Org } from "../types/types";

const data = require("../data/input.json");

const Index: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>SaltPay Challenge - Oxford Hack 2022</title>
                <meta name={"description"} content={"Generated by create next app"} />
                <link rel={"icon"} href={"/favicon.ico"} />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    SaltPay Challenge
                </h1>

                {/*<p>{JSON.stringify(data, null, 4)}</p>*/}

                <div>
                    {
                        data.map((element: Org, index: number) => {
                            return (
                                <Card key={index} org={element} />
                            );
                        })
                    }
                </div>
            </main>
        </div>
    );
}

export default Index;
