import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

let data = require("../input.json");
// data = JSON.parse(data);
console.log(data);

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>SaltPay Challenge - Oxford Hack 2022</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    SaltPay Challenge
                </h1>

                <p>
                    {JSON.stringify(data, null, 4)}
                </p>
            </main>
        </div>
    )
}

export default Home
